Python Algorithm Development Guide Updates
algorithmiaio/dev-center pull request #359
Opened 2020-11-30 17:23 UTC by noahcrowley

Updates screenshots.

Updates "Available Libraries" section; I noticed there is a new "Environment Matrix" page which has details about supported environments, so I linked to that in addition to providing a screenshot of the drop-down menu in the algorithm creation modal.

Adds a new "Working with directories" section; @StephanieKim can you make sure I'm on the right track with this?

2020-12-01 17:39 UTC, bnlb approved these changes
LGTM!

2020-12-09 01:38 UTC, StephanieKim requested changes

2020-12-09 01:38 UTC, StephanieKim commented on _pages/algorithm-development/languages/python.md
> +Algorithmia makes a number of libraries available to make algorithm development easier. We support multiple versions of Python and a variety of frameworks, and we continue to add new variants and bro
```suggestion
Algorithmia makes a number of libraries available to make algorithm development easier. We support multiple versions of Python and a variety of frameworks, and we continue to add new variants and broaden GPU support. A complete list of supported environments can be found on the [Environment Matrix](/developers/model-deployment/environments/) page, and are available through the "Environment" drop-down when creating a new algorithm.
```

2020-12-09 01:40 UTC, StephanieKim commented
@noahcrowley sorry i dropped the ball on reviewing this - didn't see the request to review until tonight! Only a slight misspelling to be fixed thanks and yeah, i love the data portion looks great!

2020-12-09 16:32 UTC, StephanieKim approved these changes

2020-12-09 16:32 UTC, merged