Update Java Client Guide
algorithmiaio/dev-center pull request #399
Opened 2021-01-30 02:21 UTC by noahcrowley

2021-02-01 18:20 UTC, StephanieKim requested changes

2021-02-01 18:20 UTC, stevielkim commented on _pages/clients/java.md
>  ## Publishing Algorithmia Insights
My bad, I updated the Python client sample, and forgot about the java and r one. Can we change it to this, but for java? 

## Publishing Algorithmia Insights

This feature is available to [Algorithmia Enterprise](/enterprise) users only. 
{: .notice-enterprise}

Inference-related metrics (a feature of [Algorithmia Insights](../algorithmia-enterprise/algorithmia-insights)) can be reported via using the `report_insights` method of the Algorithmia client. 

Depending on your algorithm, you might want to report on the algorithm payload for each API call (such as the features or number of features), the output of the algorithm to monitor data distributions of predictions, or probability of each inference.

In the case of an example credit scoring model, shown in this demo for <a href-"https://www.youtube.com/watch?v=pdKwtp-_n2M ">Algorithmia Insights</a>, reported metrics include the algorithm predictions:

{% highlight python %}
# Report Algorithmia Insights
client.report_insights({"risk_score": risk_score, "approved": approved})
{% endhighlight %}

{% highlight python %}
# Sample model output that is pushed to Insights
{
  "approved": 1,
  "risk_score": 0.08
}
{% endhighlight %}

2021-02-01 20:05 UTC, noahcrowley commented on _pages/clients/java.md
>  ## Publishing Algorithmia Insights
Updated

2021-02-01 22:58 UTC, bnlb approved these changes

2021-02-02 17:21 UTC, StephanieKim approved these changes

2021-02-02 18:10 UTC, merged