Update Scala client guide
algorithmiaio/dev-center pull request #402
Opened 2021-02-01 16:49 UTC by noahcrowley

2021-02-01 18:19 UTC, StephanieKim requested changes

2021-02-01 18:19 UTC, StephanieKim commented on _pages/clients/scala.md
> +val client = Algorithmia.client("simHz3+QqlC96HCx2j+jc58d7tA1")
remove api key

2021-02-01 18:19 UTC, StephanieKim commented on _pages/clients/scala.md
> +val imgDirectory = client.dir("data://noahcrowley/img_directory")
```suggestion
val imgDirectory = client.dir("data://YOUR_USERNAME/img_directory")
```

2021-02-01 19:52 UTC, noahcrowley commented on _pages/clients/scala.md
> +val client = Algorithmia.client("simHz3+QqlC96HCx2j+jc58d7tA1")
Whoops!

2021-02-01 22:59 UTC, bnlb approved these changes

2021-02-02 17:20 UTC, StephanieKim approved these changes

2021-02-02 18:10 UTC, merged