Add Datadog and InfluxDB integrations pages
algorithmiaio/dev-center pull request #418
Opened 2021-02-15 15:27 UTC by noahcrowley

Adds new pages, screenshots, and "language_logos" SVGs for Datadog and InfluxData.

2021-02-16 02:55 UTC, StephanieKim requested changes

2021-02-16 02:55 UTC, stevielkim commented on _pages/integrations/datadog.md
> +When algorithms that have Insights enabled are queried, Algorithmia emits a metrics payload to a configured Kafka broker and topic. The [Algorithmia-Datadog integration](https://docs.datadoghq.com/in
```suggestion
When algorithms that have Insights enabled are run, Algorithmia emits a metrics payload to a configured Kafka broker and topic. The [Algorithmia-Datadog integration](https://docs.datadoghq.com/integrations/algorithmia/) then transforms and forwards Insights data from Kafka to the [Datadog metrics API endpoint](https://docs.datadoghq.com/api/v1/metrics/). All of the data from Algorithmia Insights will show up in Datadog as metrics with the prefix `algorithmia`. This makes it easy to include model performance data from Algorithmia Insights in dashboards or monitors.
```

2021-02-16 02:55 UTC, stevielkim commented on _pages/integrations/datadog.md
> +[Algorithmia Insights](https://algorithmia.com/blog/introducing-algorithmia-insights-datadog-integration) is a new feature of Algorithmia Enterprise and provides a metrics pipeline that can be used t
```suggestion
[Algorithmia Insights](https://algorithmia.com/blog/introducing-algorithmia-insights-datadog-integration) is a new feature of Algorithmia Enterprise that provides a metrics pipeline that can be used to instrument, measure, and monitor your machine learning models. Monitoring your model performance metrics can help with your organization’s overall [AI/ML governance efforts](https://algorithmia.com/blog/model-governance), and use cases include detecting [model drift](https://algorithmia.com/blog/model-drift-and-ensuring-a-healthy-machine-learning-lifecycle), data drift, and model bias.
```

2021-02-16 02:55 UTC, stevielkim commented on _pages/integrations/datadog.md
> +1. Configure Algorithmia to send Insights to a Kafka broker and topic
Link to https://algorithmia.com/developers/algorithmia-enterprise/algorithmia-insights in step #1

2021-02-16 02:55 UTC, stevielkim commented on _pages/integrations/datadog.md
> +
Lets add the enterprise only banner here like on Insights page https://algorithmia.com/developers/algorithmia-enterprise/algorithmia-insights

2021-02-16 02:55 UTC, StephanieKim commented on _pages/integrations/datadog.md
> +3. From Algorithmia, you can then instrument, publish, and query algorithms that have Insights enabled
```suggestion
3. For any published algorithm on your cluster that has Insights enabled, once the algorithm's API is called, those metrics will be pushed to DataDog. 
```

2021-02-16 02:55 UTC, StephanieKim commented on _pages/integrations/datadog.md
> +Click on the **Save** button, then the data from Insights should show up in your new widget. You might need to query your model in Algorithmia to see data flowing into Datadog.
```suggestion
Click on the **Save** button, then the data from Insights should show up in your new widget. You might need to call your algorithm on your Algorithmia cluster to see data flowing into Datadog.
```

2021-02-16 02:55 UTC, StephanieKim commented on _pages/integrations/influxdb.md
> +
Lets add the enterprise only banner here like on Insights page https://algorithmia.com/developers/algorithmia-enterprise/algorithmia-insights

2021-02-16 02:55 UTC, StephanieKim commented on _pages/integrations/influxdb.md
> +3. From Algorithmia, you can then instrument, publish, and query algorithms that have Insights enabled
```suggestion
3. For any published algorithm on your cluster that has Insights enabled, once the algorithm's API is called, those metrics will be pushed to DataDog. 
```
or something along those lines, more explicit

2021-02-17 17:48 UTC, bnlb commented on _pages/integrations/datadog.md
> +<img src="{{site.cdnurl}}{{site.baseurl}}/images/post_images/datadog/algorithmia-datadog-integration.png" alt="Flow chart of Datadog-Algorithmia integration for model performance metrics" class="scre
Great job on these alt attributes. 💯

2021-02-17 17:53 UTC, bnlb approved these changes

2021-02-23 02:08 UTC, StephanieKim approved these changes

2021-02-23 02:08 UTC, merged