Update cURL client guide
algorithmiaio/dev-center pull request #449
Opened 2021-03-16 15:06 UTC by noahcrowley

2021-03-16 17:08 UTC, bnlb commented on _pages/clients/curl.md
> +Your account can make up to {{site.data.stats.platform.max_num_algo_requests}} Algorithmia requests at the same time (this limit <a onclick="Intercom('show')">can be raised</a> if needed).
`Intercom` is undefined in the global scope in prod. Let's change the link slightly:
```suggestion
Your account can make up to {{site.data.stats.platform.max_num_algo_requests}} Algorithmia requests at the same time (this limit <a href="mailto:support@algorithmia.com?subject=Request to raise max algorithm request limit">can be raised</a> if needed).
```

2021-03-16 17:09 UTC, bnlb requested changes
Only blocker is that Intercom link which is a quick update. Everything else looks good 👍

2021-03-23 21:45 UTC, StephanieKim submitted a review, later dismissed

2021-03-25 20:45 UTC, StephanieKim commented
@noahcrowley can you see what changes need to be made and finish this one up please? Thanks!

2021-03-29 22:53 UTC, noahcrowley commented
Should be good to go, thanks!

2021-03-30 17:01 UTC, StephanieKim commented
@bnlb can you review this PR please? it's not a big one, but requires your review thanks!

2021-03-30 17:15 UTC, bnlb approved these changes
Thanks for the reminder @StephanieKim. lgtm!

2021-03-30 17:16 UTC, merged