fixed spelling and grammatical errors
algorithmiaio/dev-center pull request #608
Opened 2022-01-01 17:12 UTC by ShubhGurukul

fixed spelling and grammatical errors

[DOCS-XXX](https://algorithmia.atlassian.net/browse/DOCS-XXX) - Brief description / title of ticket

Additional context/notes if appropriate (e.g., specifics about what's changing, links to epic or other PRs, etc.)

## Checklist
- [ ] My PR title includes a relevant Jira ticket name
- [ ] If no associated Jira ticket, my PR title is informative (individual commit messages are squashed in this repo)
- [ ] Unnecessary text (notes, TODOs, etc.) has been removed
- [ ] For YAML "front matter":
  - Properties are alphabetized
  - `permalink` and `redirect_from/to` properties have `/` at beginning and end (e.g., `/path/`)
- [ ] Screenshots, if present, follow the [Screenshot guidelines](https://algorithmia.atlassian.net/wiki/spaces/CUSTOMERS/pages/1634861478/CFD+Style+Guide#Screenshots) which means:
  - Full browser width (browser at 100% zoom and 10-12" width)
  - Max 1000px
- [ ] Grammar, style, tone, punctuation, etc. follow the Algorithmia [manual of style](https://docs.google.com/document/d/1PPVfgMkX7-EVGLPMhN1E485CAXu9QfhSLKM0lZhnZdU/edit?usp=sharing)
- [ ] Headers are “Sentence case with Proper Nouns capitalized”
- [ ] Placeholder strings are `UPPER_SNAKE_CASE` and are named as in the [Glossary](https://algorithmia.com/developers/glossary) where appropriate

2022-01-02 20:58 UTC, lemonez commented on _pages/platform/organization-profile.md
> +If you're looking to share algorithms privately or publish algorithms on behalf of an organization, such as a university, private company, or open-source community, then you should consider using our
This is actually already correct as is; "organizations" is what we call the feature, so it's plural and not possessive.

2022-01-02 20:58 UTC, lemonez commented on _pages/platform/organization-profile.md
> +If you're looking to share algorithms privately or publish algorithms on behalf of an organization, such as a university, private company, or open-source community, then you should consider using our
```suggestion
If you're looking to share algorithms privately or publish algorithms on behalf of an organization, such as a university, private company, or open-source community, then you should consider using our organizations feature.
```

2022-01-02 20:59 UTC, lemonez commented on _pages/platform/organization-profile.md
> +The profile overview provides a rich source of information about an organization. In the overview, you can find the name of an organization, its members, and a list of the algorithms under its owners
Thanks!

2022-01-02 21:01 UTC, lemonez commented on _pages/platform/organization-profile.md
> +You can invite users to your organization by clicking the **Invite Member** button at the upper-right corner of the organization profile. You can invite members either by using their Algorithmia acco
```suggestion
You can invite users to your organization by clicking the **Invite Member** button at the upper-right corner of the organization profile. You can invite a member either by using their Algorithmia account name or by providing their email address. Users invited by account name will receive an email and as well as an in-platform notification to join the organization.
```
Thanks; the use of "their" was intended to be singular and gender neutral, but I see it wasn't clear. I've updated the wording to be clearer, how does this sound?

2022-01-02 21:03 UTC, lemonez commented on _pages/platform/organization-profile.md
> +At this time you'll be able to set the royalty (if any) if you're using our non-Enterprise platform and finalize publishing.
Thanks; everything after this point actually applies to our deprecated public marketplace platform and will be going away, but I can make those changes myself.

2022-01-02 21:03 UTC, lemonez requested changes
Thanks for your contribution!

2022-01-03 21:43 UTC, ToshMeston submitted a review, later dismissed
👍 🚢

2022-01-03 23:48 UTC, merged